#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-geronimo-spec-jaxrpc
Version  : 1.1.r4
Release  : 1
URL      : https://repo1.maven.org/maven2/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.jar
Source0  : https://repo1.maven.org/maven2/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.jar
Source1  : https://repo1.maven.org/maven2/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-geronimo-spec-jaxrpc-data = %{version}-%{release}
Requires: mvn-geronimo-spec-jaxrpc-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-geronimo-spec-jaxrpc package.
Group: Data

%description data
data components for the mvn-geronimo-spec-jaxrpc package.


%package license
Summary: license components for the mvn-geronimo-spec-jaxrpc package.
Group: Default

%description license
license components for the mvn-geronimo-spec-jaxrpc package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-geronimo-spec-jaxrpc
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-geronimo-spec-jaxrpc/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.jar
/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-geronimo-spec-jaxrpc/LICENSE.txt
